"""Hairstyle endpoints."""

import json

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import Hairstyle
from app.schemas import HairstyleListResponse, HairstyleOut, success_response

router = APIRouter(prefix="/api/v1", tags=["Hairstyles"])

# Seed data for hairstyle library (30+ styles)
MOCK_HAIRSTYLES = [
    {
        "id": "hs-001",
        "name": "清爽短发",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "work",
        "description": "干净利落，适合职场与日常，凸显面部轮廓。",
        "cover_image_url": "https://images.unsplash.com/photo-1599351431202-6e0c7f8d5f6a?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1599351431202-6e0c7f8d5f6a?w=200",
        "tags": ["职场", "清爽", "易打理"],
        "face_type_suitability": ["oval", "square", "diamond"],
        "prompt_for_generation": "A man with a clean short haircut, neat sides, professional look, studio lighting, high quality portrait, realistic photography",
        "sort_order": 1,
    },
    {
        "id": "hs-002",
        "name": "微卷中长发",
        "category": "female",
        "style": "curly",
        "length": "medium",
        "scene": "date",
        "description": "温柔浪漫，微卷增加发量感，适合约会和聚会。",
        "cover_image_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=200",
        "tags": ["浪漫", "温柔", "显发量"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A woman with medium length wavy hair, soft loose curls, romantic style, warm lighting, elegant portrait, realistic photography",
        "sort_order": 2,
    },
    {
        "id": "hs-003",
        "name": "韩式空气刘海长发",
        "category": "female",
        "style": "straight",
        "length": "long",
        "scene": "daily",
        "description": "空气刘海搭配长直发，减龄又百搭。",
        "cover_image_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200",
        "tags": ["减龄", "百搭", "甜美"],
        "face_type_suitability": ["oval", "long", "heart"],
        "prompt_for_generation": "A young woman with long straight black hair and airy Korean-style bangs, youthful and fresh look, soft natural lighting, realistic photography",
        "sort_order": 3,
    },
    {
        "id": "hs-004",
        "name": "油头背头",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "work",
        "description": "经典商务造型，气场全开，适合正式场合。",
        "cover_image_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
        "tags": ["商务", "气场", "正式"],
        "face_type_suitability": ["oval", "square", "round"],
        "prompt_for_generation": "A man with a classic slicked-back hairstyle, pomade shine, sharp formal look, studio lighting, confident expression, realistic photography",
        "sort_order": 4,
    },
    {
        "id": "hs-005",
        "name": "羊毛卷",
        "category": "unisex",
        "style": "curly",
        "length": "medium",
        "scene": "party",
        "description": "蓬松羊毛卷，个性十足，适合潮流达人。",
        "cover_image_url": "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=200",
        "tags": ["潮流", "个性", "蓬松"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A person with voluminous woolly curls, trendy street style, bold and expressive, modern fashion lighting, realistic photography",
        "sort_order": 5,
    },
    {
        "id": "hs-006",
        "name": "碎盖发型",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "daily",
        "description": "层次感碎盖，修饰脸型，少年感满满。",
        "cover_image_url": "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=200",
        "tags": ["少年感", "修饰脸型", "层次"],
        "face_type_suitability": ["round", "oval", "heart"],
        "prompt_for_generation": "A young man with textured layered crop haircut, fringe falling on forehead, youthful Korean style, natural daylight, realistic photography",
        "sort_order": 6,
    },
    {
        "id": "hs-007",
        "name": "法式慵懒卷发",
        "category": "female",
        "style": "curly",
        "length": "long",
        "scene": "date",
        "description": "随性自然的法式卷，慵懒中透着优雅，拍照超级出片。",
        "cover_image_url": "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=200",
        "tags": ["法式", "慵懒", "出片"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A woman with long French-style loose curls, effortless chic, soft bohemian vibe, golden hour lighting, realistic photography",
        "sort_order": 7,
    },
    {
        "id": "hs-008",
        "name": "高马尾",
        "category": "female",
        "style": "straight",
        "length": "long",
        "scene": "daily",
        "description": "元气满满的高马尾，清爽利落，显脸小神器。",
        "cover_image_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
        "tags": ["元气", "清爽", "显脸小"],
        "face_type_suitability": ["round", "oval", "heart"],
        "prompt_for_generation": "A young woman with a high ponytail, sleek and energetic, clean facial features, bright studio lighting, realistic photography",
        "sort_order": 8,
    },
    {
        "id": "hs-009",
        "name": "丸子头",
        "category": "female",
        "style": "braid",
        "length": "long",
        "scene": "daily",
        "description": "经典丸子头，可爱又减龄，夏日清凉首选。",
        "cover_image_url": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200",
        "tags": ["可爱", "减龄", "清凉"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A woman with a neat top bun hairstyle, cute and fresh look, minimal makeup, soft natural lighting, realistic photography",
        "sort_order": 9,
    },
    {
        "id": "hs-010",
        "name": "脏辫",
        "category": "unisex",
        "style": "braid",
        "length": "medium",
        "scene": "party",
        "description": "个性张扬的脏辫造型，街头潮流感十足。",
        "cover_image_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=200",
        "tags": ["街头", "个性", "潮流"],
        "face_type_suitability": ["oval", "square", "diamond"],
        "prompt_for_generation": "A person with stylish dreadlocks, urban street fashion, confident attitude, dramatic lighting, realistic photography",
        "sort_order": 10,
    },
    {
        "id": "hs-011",
        "name": "lob 短发",
        "category": "female",
        "style": "straight",
        "length": "medium",
        "scene": "work",
        "description": "及肩 lob 头，干练又不失女人味，职场女性首选。",
        "cover_image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",
        "tags": ["干练", "职场", "知性"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A professional woman with a sleek lob haircut just above shoulders, sophisticated and modern, office setting, realistic photography",
        "sort_order": 11,
    },
    {
        "id": "hs-012",
        "name": "男士侧分油头",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "work",
        "description": "三七分油头，复古绅士感，成熟魅力加分。",
        "cover_image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        "tags": ["复古", "绅士", "成熟"],
        "face_type_suitability": ["oval", "square", "round"],
        "prompt_for_generation": "A gentleman with a classic side-parted slick hairstyle, vintage sophistication, warm lighting, realistic photography",
        "sort_order": 12,
    },
    {
        "id": "hs-013",
        "name": "大波浪卷发",
        "category": "female",
        "style": "curly",
        "length": "long",
        "scene": "party",
        "description": " glamorous 大波浪，派对女王气场，回头率爆表。",
        "cover_image_url": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200",
        "tags": [" Glamorous", "女王", "回头率"],
        "face_type_suitability": ["oval", "long", "heart"],
        "prompt_for_generation": "A glamorous woman with big voluminous waves, red carpet style, dramatic evening lighting, realistic photography",
        "sort_order": 13,
    },
    {
        "id": "hs-014",
        "name": "寸头",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "daily",
        "description": "极简寸头，考验颜值的发型，清爽到极致。",
        "cover_image_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        "tags": ["极简", "考验颜值", "清爽"],
        "face_type_suitability": ["oval", "square", "diamond"],
        "prompt_for_generation": "A man with a very short buzz cut, minimalist and bold, strong jawline emphasized, clean studio lighting, realistic photography",
        "sort_order": 14,
    },
    {
        "id": "hs-015",
        "name": "公主切",
        "category": "female",
        "style": "straight",
        "length": "long",
        "scene": "daily",
        "description": "日式公主切，二次元感满满，个性又神秘。",
        "cover_image_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=200",
        "tags": ["二次元", "神秘", "个性"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A woman with Japanese hime cut, straight long hair with cheek-level side locks, mysterious anime-inspired look, realistic photography",
        "sort_order": 15,
    },
    {
        "id": "hs-016",
        "name": "男士纹理烫",
        "category": "male",
        "style": "curly",
        "length": "short",
        "scene": "date",
        "description": "蓬松纹理烫，增加发量感，约会造型利器。",
        "cover_image_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200",
        "tags": ["蓬松", "约会", "发量感"],
        "face_type_suitability": ["round", "oval", "heart"],
        "prompt_for_generation": "A young man with textured perm hairstyle, voluminous and stylish, casual dating look, warm lighting, realistic photography",
        "sort_order": 16,
    },
    {
        "id": "hs-017",
        "name": "低盘发",
        "category": "female",
        "style": "braid",
        "length": "long",
        "scene": "work",
        "description": "优雅低盘发，知性大方，职场面试约会通用。",
        "cover_image_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=200",
        "tags": ["优雅", "知性", "通用"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A woman with an elegant low chignon bun, sophisticated and polished, professional setting, soft lighting, realistic photography",
        "sort_order": 17,
    },
    {
        "id": "hs-018",
        "name": "挂耳染",
        "category": "unisex",
        "style": "dye",
        "length": "medium",
        "scene": "party",
        "description": "低调又个性的挂耳染，若隐若现的色彩心机。",
        "cover_image_url": "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=200",
        "tags": ["心机染", "个性", "低调"],
        "face_type_suitability": ["oval", "round", "square"],
        "prompt_for_generation": "A person with hidden under-dye highlights peeking from behind ears, subtle color accents, trendy and cool, realistic photography",
        "sort_order": 18,
    },
    {
        "id": "hs-019",
        "name": "高层次长发",
        "category": "female",
        "style": "straight",
        "length": "long",
        "scene": "daily",
        "description": "高层次剪裁让长发更有动感，轻盈不沉闷。",
        "cover_image_url": "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=200",
        "tags": ["动感", "轻盈", "层次感"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A woman with long layered haircut, movement and flow, natural texture, outdoor daylight, realistic photography",
        "sort_order": 19,
    },
    {
        "id": "hs-020",
        "name": "鲻鱼头",
        "category": "unisex",
        "style": "straight",
        "length": "medium",
        "scene": "party",
        "description": "复古又前卫的鲻鱼头，摇滚范儿十足。",
        "cover_image_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=200",
        "tags": ["摇滚", "前卫", "复古"],
        "face_type_suitability": ["oval", "square", "diamond"],
        "prompt_for_generation": "A person with a retro mullet hairstyle, edgy rock and roll vibe, bold fashion, dramatic lighting, realistic photography",
        "sort_order": 20,
    },
    {
        "id": "hs-021",
        "name": "男士飞机头",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "daily",
        "description": "经典飞机头，立体有型，日常帅气选择。",
        "cover_image_url": "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=200",
        "tags": ["帅气", "立体", "经典"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A man with a classic quiff hairstyle, height and volume on top, clean sides, everyday handsome look, realistic photography",
        "sort_order": 21,
    },
    {
        "id": "hs-022",
        "name": "蛋卷头",
        "category": "female",
        "style": "curly",
        "length": "medium",
        "scene": "date",
        "description": "可爱蛋卷头，蓬松圆润，甜美感拉满。",
        "cover_image_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200",
        "tags": ["可爱", "甜美", "蓬松"],
        "face_type_suitability": ["round", "oval", "heart"],
        "prompt_for_generation": "A woman with egg curl bob hairstyle, bouncy and round curls, adorable and sweet, soft pastel lighting, realistic photography",
        "sort_order": 22,
    },
    {
        "id": "hs-023",
        "name": "男士渐变短发",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "daily",
        "description": "渐变 fade 短发，干净利落，型男必备。",
        "cover_image_url": "https://images.unsplash.com/photo-1599351431202-6e0c7f8d5f6a?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1599351431202-6e0c7f8d5f6a?w=200",
        "tags": ["型男", "渐变", "干净"],
        "face_type_suitability": ["oval", "square", "diamond"],
        "prompt_for_generation": "A man with a fade haircut, clean tapered sides, sharp and modern, barbershop quality, realistic photography",
        "sort_order": 23,
    },
    {
        "id": "hs-024",
        "name": "水母头",
        "category": "female",
        "style": "straight",
        "length": "medium",
        "scene": "party",
        "description": "上下分层的水母头，个性前卫，艺术感十足。",
        "cover_image_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=200",
        "tags": ["前卫", "艺术", "分层"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A woman with a jellyfish haircut, distinct upper and lower layers, avant-garde artistic style, editorial fashion lighting, realistic photography",
        "sort_order": 24,
    },
    {
        "id": "hs-025",
        "name": "拳击辫",
        "category": "female",
        "style": "braid",
        "length": "long",
        "scene": "daily",
        "description": "帅气拳击辫，运动风满满，酷女孩专属。",
        "cover_image_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
        "tags": ["运动", "酷女孩", "帅气"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A woman with tight boxer braids, sporty and cool aesthetic, athletic vibe, bright daylight, realistic photography",
        "sort_order": 25,
    },
    {
        "id": "hs-026",
        "name": "樱花粉渐变染发",
        "category": "female",
        "style": "dye",
        "length": "long",
        "scene": "party",
        "description": "梦幻樱花粉渐变，仙女发色，派对焦点。",
        "cover_image_url": "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=200",
        "tags": ["仙女", "梦幻", "焦点"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A woman with long hair in cherry blossom pink ombre gradient, dreamy and ethereal, pastel tones, soft romantic lighting, realistic photography",
        "sort_order": 26,
    },
    {
        "id": "hs-027",
        "name": "男士中分长发",
        "category": "male",
        "style": "straight",
        "length": "long",
        "scene": "daily",
        "description": "文艺中分长发，随性洒脱，艺术家气质。",
        "cover_image_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
        "tags": ["文艺", "洒脱", "艺术家"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A man with long center-parted hair, artistic and free-spirited, bohemian style, natural outdoor lighting, realistic photography",
        "sort_order": 27,
    },
    {
        "id": "hs-028",
        "name": "波波头",
        "category": "female",
        "style": "straight",
        "length": "short",
        "scene": "work",
        "description": "经典波波头，知性优雅，永不过时的选择。",
        "cover_image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",
        "tags": ["经典", "知性", "优雅"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A woman with a classic bob haircut, chin-length, sleek and elegant, timeless style, professional studio lighting, realistic photography",
        "sort_order": 28,
    },
    {
        "id": "hs-029",
        "name": "拉美卷",
        "category": "unisex",
        "style": "curly",
        "length": "medium",
        "scene": "party",
        "description": "热情奔放的拉美卷，活力四射，舞池焦点。",
        "cover_image_url": "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=200",
        "tags": ["热情", "活力", "焦点"],
        "face_type_suitability": ["oval", "long", "diamond"],
        "prompt_for_generation": "A person with tight Latina curls, voluminous and vibrant, energetic party vibe, colorful lighting, realistic photography",
        "sort_order": 29,
    },
    {
        "id": "hs-030",
        "name": "男士露额短发",
        "category": "male",
        "style": "straight",
        "length": "short",
        "scene": "work",
        "description": "露额短发，清爽精神，商务休闲两相宜。",
        "cover_image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        "tags": ["清爽", "精神", "商务"],
        "face_type_suitability": ["oval", "square", "round"],
        "prompt_for_generation": "A man with a short forehead-exposing haircut, clean and fresh, business casual style, bright office lighting, realistic photography",
        "sort_order": 30,
    },
    {
        "id": "hs-031",
        "name": "双麻花辫",
        "category": "female",
        "style": "braid",
        "length": "long",
        "scene": "daily",
        "description": "俏皮双麻花辫，田园少女风，清新自然。",
        "cover_image_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200",
        "tags": ["俏皮", "田园", "清新"],
        "face_type_suitability": ["oval", "round", "heart"],
        "prompt_for_generation": "A young woman with two loose braids, pastoral and innocent, natural outdoor setting, golden hour, realistic photography",
        "sort_order": 31,
    },
    {
        "id": "hs-032",
        "name": "奶奶灰染发",
        "category": "unisex",
        "style": "dye",
        "length": "short",
        "scene": "party",
        "description": "潮酷奶奶灰，高级感拉满，潮流先锋。",
        "cover_image_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400",
        "thumbnail_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200",
        "tags": ["潮酷", "高级", "先锋"],
        "face_type_suitability": ["oval", "square", "diamond"],
        "prompt_for_generation": "A person with silver grey dyed hair, trendy and high-fashion, modern avant-garde, cool-toned lighting, realistic photography",
        "sort_order": 32,
    },
]


def _ensure_seed_data(db: Session) -> None:
    """Ensure mock hairstyles exist in DB."""
    for item in MOCK_HAIRSTYLES:
        existing = db.query(Hairstyle).filter(Hairstyle.id == item["id"]).first()
        if not existing:
            row = dict(item)
            for json_field in ("tags", "face_type_suitability"):
                if isinstance(row.get(json_field), list):
                    row[json_field] = json.dumps(row[json_field], ensure_ascii=False)
            db.add(Hairstyle(**row))
    db.commit()


@router.get("/hairstyles")
async def list_hairstyles(
    category: str | None = Query(None, description="Filter by category: male, female, unisex"),
    style: str | None = Query(None, description="Filter by style: straight, curly, braid, dye"),
    length: str | None = Query(None, description="Filter by length: short, medium, long"),
    scene: str | None = Query(None, description="Filter by scene: daily, work, date, party"),
    face_type: str | None = Query(None, description="Filter by face type: oval, round, square, heart, long, diamond"),
    keyword: str | None = Query(None, description="Search by name or description keyword"),
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
) -> dict:
    """List hairstyles with optional filtering and pagination."""
    _ensure_seed_data(db)

    query = db.query(Hairstyle)
    if category:
        query = query.filter(Hairstyle.category == category)
    if style:
        query = query.filter(Hairstyle.style == style)
    if length:
        query = query.filter(Hairstyle.length == length)
    if scene:
        query = query.filter(Hairstyle.scene == scene)
    if face_type:
        query = query.filter(
            or_(
                Hairstyle.face_type_suitability.ilike(f"%{face_type}%"),
                Hairstyle.face_type_suitability == face_type,
            )
        )
    if keyword:
        like_keyword = f"%{keyword}%"
        query = query.filter(
            or_(
                Hairstyle.name.ilike(like_keyword),
                Hairstyle.description.ilike(like_keyword),
                Hairstyle.tags.ilike(like_keyword),
            )
        )

    total = query.count()
    items = (
        query.order_by(Hairstyle.sort_order.asc())
        .offset((page - 1) * per_page)
        .limit(per_page)
        .all()
    )

    return success_response(
        data=HairstyleListResponse(
            items=[HairstyleOut.model_validate(item) for item in items],
            total=total,
        ),
        meta={"page": page, "per_page": per_page, "total": total},
    )
